## Debug exercise

The functions below convert Eucledian coordinates to [homogenious](https://en.wikipedia.org/wiki/Homogeneous_coordinates). 
However, the functions sometimes return NaNs. 
Find the cause for this, create a minimal reproducing example, discuss the possible fixes and fix the issue.

In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F



def convert_points_to_homogeneous(points):
    r"""Function that converts points from Euclidean to homogeneous space.
    See :class:`~torchgeometry.ConvertPointsToHomogeneous` for details.
    Examples::
        >>> inp = torch.rand(2, 4, 3)  # BxNx3
        >>> output = convert_points_to_homogeneous(inp)  # BxNx4
    """
    if not torch.is_tensor(points):
        raise TypeError("Input type is not a torch.Tensor. Got {}".format(
            type(points)))
    if len(points.shape) < 2:
        raise ValueError("Input must be at least a 2D tensor. Got {}".format(
            points.shape))

    return F.pad(points, (0, 1), "constant", 1.0)



def convert_points_from_homogeneous(points: torch.Tensor) -> torch.Tensor:
    r"""Function that converts points from homogeneous to Euclidean space.
    See :class:`~torchgeometry.ConvertPointsFromHomogeneous` for details.
    Examples::
        >>> inp = torch.rand(2, 4, 3)  # BxNx3
        >>> output = convert_points_from_homogeneous(inp)  # BxNx2
    """
    if not torch.is_tensor(points):
        raise TypeError("Input type is not a torch.Tensor. Got {}".format(
            type(points)))
    if len(points.shape) < 2:
        raise ValueError("Input must be at least a 2D tensor. Got {}".format(
            points.shape))

    return points[..., :-1] / points[..., -1:]

In [39]:
inp = torch.rand(2, 4, 3)
h_points = convert_points_to_homogeneous(inp)

print(h_points)

h_points = torch.tensor([[
    [1, 1, 1, 1],
    [1, 1, 1, 1],
    [1, 1, 1, 1],
    [1, 1, 1, 1],
],
[
    [1, 1, 1, 1],
    [1, 1, 1, 1],
    [1, 1, 1, 1],
    [1, 1, 1, 1],
]])

print(h_points)

point = convert_points_from_homogeneous(h_points)

print(point)

# torch.testing.assert_close(point, inp)

tensor([[[0.6352, 0.0822, 0.6038, 1.0000],
         [0.9194, 0.1935, 0.7785, 1.0000],
         [0.1535, 0.9175, 0.5523, 1.0000],
         [0.6233, 0.5845, 0.0684, 1.0000]],

        [[0.9977, 0.3554, 0.8924, 1.0000],
         [0.2165, 0.9018, 0.6916, 1.0000],
         [0.6659, 0.1310, 0.6085, 1.0000],
         [0.1994, 0.4598, 0.1362, 1.0000]]])
tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]])
tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]])
